name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: |
          npm run build
          mkdir build
          cp -R dist/* build/
      - name: Commit build changes
        run: |
          git config --global user.name "fuadariqoh"
          git config --global user.email "fuadariqoh@gmail.com"
          git add build/
          git commit -m "Add build folder"
          git push origin main
